### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by vysec** [jaredhaight/PSPunch#1]
Hi,

Sorry for being development noob.

Do you have the encrypt utility that you use to encrypt the .ps1 files with the key? I would like to explore the encoded .ps1 files further.

**Comment by jaredhaight** [comment]
No worries, I'm a noob myself. :smile:

So encryption is done with [PS>Attack](https://github.com/jaredhaight/PSAttack) when it generates PS>Punch. The relevant function is EncryptFile() in: [CryptoUtils.cs](https://github.com/jaredhaight/PSAttack/blob/master/PSAttack/Utils/CryptoUtils.cs)

The key is generated in that same file with the GenerateKey() function, which checks for a "key.txt" file and if it doesn't exist generates a 64 char string and saves it to the file.

The idea is when PS>Punch is built by PS>Attack, the encrypted files and key will be bundled with the executable. Right now this is done manually by generating the files with PS>Attack and copying them over to the PS>Punch project. 

Since the point of the encryption here isn't to prevent access to the files but to obfuscate them from AV, storing the key with the exe isn't a big deal but I may implement a different way of handling that down the road.

Thanks for the question! Let me know if you have any more.
